fixtures:
    symlinks:
      test_repl: "#{source_dir}"
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.11
      repl:
        repo: https://github.com/nwops/puppet-repl-module
    forge_modules:
